name: Go
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  build:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: build
        run: go build ./...
      - name: test
        if: ${{ matrix.os != 'windows-2025' }}
        run: go test -race -v ./...
